import streamlit as st
st.title('Streamlit Example')
st.header('Rating different animes')
st.write("**Open the sidebar to select genre on your left top corner**")
genre = st.sidebar.selectbox(
     "What's your favorite anime genre",
     ('None','Shounen', 'Romance', 'Sports'))
st.write('**You selected:**', genre)
if genre == 'Shounen':
  st.subheader('Genre:- Shounen')
  st.image('https://d.newsweek.com/en/full/1034569/attack-on-titan-season-3-art-poster-how-to-watch-online-hulu-crunchyroll-funimation-01.jpg?w=1600&h=900&q=88&f=99dce8214a86314128b26cd47296ede6')
  S1=st.slider('Attack on Titans',0.0,5.0,step=0.5)
  st.image('https://wallpapercave.com/wp/wp1894643.jpg')
  S2=st.slider('My Hero Academia',0.0,5.0,step=0.5)
  st.image('https://wallpapercave.com/wp/8fMMJWX.jpg')
  S3=st.slider('Naruto',0.0,5.0,step=0.5)
  st.image('https://image.winudf.com/v2/image1/bWUuYXppYXBwLnZpbmxhbmRzYWdhd2FsbHBhcGVyX3NjcmVlbl8yXzE1NzIwOTM2NzRfMDQ1/screen-2.jpg?fakeurl=1&type=.jpg')
  S4=st.slider('Vinland Saga',0.0,5.0,step=0.5)
  st.write('**Average Rating of Shounen genre** = ', (S1+S2+S3+S4)/4)
elif genre == 'Romance':
  st.subheader('Genre:- Romance')
  st.image('https://www.kolpaper.com/wp-content/uploads/2021/02/Horimiya-Wallpaper-HD.jpg')
  R1=st.slider('Horimiya',0.0,5.0,step=0.5)
  st.image('https://wallpapercave.com/wp/wp8650031.jpg')
  R2=st.slider('Bottom-Tier Character Tomozaki-kun',0.0,5.0,step=0.5)
  st.image('https://c4.wallpaperflare.com/wallpaper/166/158/478/clannad-clannad-after-story-okazaki-nagisa-okazaki-tomoya-wallpaper-preview.jpg')
  R3=st.slider('Clannad',0.0,5.0,step=0.5)
  st.image('https://images8.alphacoders.com/737/thumb-1920-737474.png')
  R4=st.slider('Kimi no Na Wa',0.0,5.0,step=0.5)
  st.write('**Average Rating of Romace genre** = ', (R1+R2+R3+R4)/4)
elif genre == 'Sports':
  st.subheader('Genre:- Sports')
  st.image('https://c4.wallpaperflare.com/wallpaper/430/354/442/haikyuu-haikyuu-hinata-shouyou-kageyama-tobio-azumane-asahi-hd-wallpaper-preview.jpg')
  SP1=st.slider('Haikyuu!',0.0,5.0,step=0.5)
  st.image('https://wallpaperaccess.com/full/1648578.jpg')
  SP2=st.slider('Diamond no Ace',0.0,5.0,step=0.5)
  st.image('https://images2.alphacoders.com/267/267400.jpg')
  SP3=st.slider('Kuroko no Baske',0.0,5.0,step=0.5)
  st.image('https://wallpapercave.com/wp/wp9165028.jpg')
  SP4=st.slider('Burning Kabaddi',0.0,5.0,step=0.5)
  st.write('**Average Rating of Sports genre** = ', (SP1+SP2+SP3+SP4)/4) 
